### ISSUE TITLE
extract perception_test audio feature  problems

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#27]
i use following command to extract audio features:
```

export CUDA_VISIBLE_DEVICES=6,7
python tools/run_net.py --cfg /data/nvme2/dky/lc/TIM/feature_extractors/auditory_slowfast/configs/PERCEPTION/SLOWFAST_R50.yaml \
NUM_GPUS 2 \
OUTPUT_DIR /data/hdd/lishenshen/timfeature_data/perception_test-feature \
PERCEPTION.AUDIO_DATA_DIR /data/hdd/lishenshen/data/perception_test/valid_audios/audios \
PERCEPTION.TEST_LIST /data/nvme2/dky/lc/TIM/annotations/Perception_Test/Perception_Test_1_second_validation_feature_times.pkl \
TEST.CHECKPOINT_FILE_PATH /data/nvme2/dky/lc/TIM/feature_extractors/auditory_slowfast/pretrained_models/asf_vggsound.pyth \
TEST.NUM_FEATURES 1
```
and then obtain files: feature.npy and metadata.npy,
then i post-process the features with numpy files using the follow command:
`python utils/make_npyfiles.py --feature_file /data/hdd/lishenshen/timfeature_data/perception_test-feature/features.npy --pickle_file /data/nvme2/dky/lc/TIM/annotations/Perception_Test/Perception_Test_1_second_validation_feature_times.pkl --out_dir /data/hdd/lishenshen/timfeature_data/perception_test-feature/val_a `

but there will be  an error :
  File "/data/nvme2/dky/lc/TIM/feature_extractors/auditory_slowfast/utils/make_npyfiles.py", line 26, in main
    assert len(feature) == len(feature_pandas)
AssertionError
 but i do not konw how to fix it ,thank you!

**Comment by MuXiangWen** [comment]
<img width="259" alt="image" src="https://github.com/JacobChalk/TIM/assets/94733207/19dad079-56b9-42e6-8835-d18cae88d9c5">
and the length of them are above

**Comment by JacobChalk** [comment]
The length of the feature array should indeed be 593655, the same as the pandas data frame. 

The extracted features were of size 57 due to [an old piece of residual test code](https://github.com/JacobChalk/TIM/blob/52754062449b1f2612ab5c1504a18d615ae7e39d/feature_extractors/auditory_slowfast/slowfast/datasets/perception.py#L44) left over. We have fixed this now so that the data loader will construct properly and extract all of the videos, rather than a single specific video. Apologies for the inconvenience!
