### ISSUE TITLE
Unsupported num_class for Mixup

### ISSUE THREAD

**Issue by HaozheQi** [JacobChalk/TIM#4]
Dear Jacob,

Thanks for this cool codebase. I am trying to train VideoMAE on EPIC following your instructions. However, I found the `args.nb_classes` you send into the `Mixup` function [here](https://github.com/JacobChalk/TIM/blob/main/feature_extractors/VideoMAE/run_class_finetuning.py#L512) is an invalid argument, since  `Mixup` can only accept `num_classes` of `int` type as is shown [here](https://github.com/huggingface/pytorch-image-models/blob/main/timm/data/mixup.py#L102), while `args.nb_classes==[97,300]` you use is a list. I wonder if you have changed anything inside the timm codebase to make it work?

Thank you in advance for your help!

**Comment by JacobChalk** [comment]
Hi,

Apologies for the delay in response, we disabled MixUp and CutMix for fine-tuning VideoMAE due to the compatibility issues. We will update the command in the ReadME accordingly. You can also find our pretrained VideoMAE model [here](https://www.dropbox.com/scl/fi/kr14exj9ipfcoth01thld/videomae_epic.pth.tar?rlkey=d9jqjqp2b3zy1440qcbdog3x4&dl=0).
